# Generated by Django 3.1.7 on 2023-05-29 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaluser',
            name='rol',
        ),
        migrations.RemoveField(
            model_name='user',
            name='rol',
        ),
    ]
