# Generated by Django 3.1.7 on 2023-06-27 01:21

import apps.Mascota.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('idMascota', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('fotografia', models.ImageField(blank=True, null=True, upload_to=apps.Mascota.models.upload_to)),
                ('nombre', models.CharField(max_length=200)),
                ('sexo', models.CharField(choices=[('Macho', 'Macho'), ('Hembra', 'Hembra')], default='Macho', max_length=200)),
                ('edad', models.IntegerField()),
                ('talla', models.CharField(choices=[('Chica', 'Chica'), ('Mediano', 'Mediano'), ('Grande', 'Grande')], default='Chica', max_length=20)),
            ],
        ),
    ]
